plugins {
    id 'java'
    id 'java-library'
    id 'maven-publish'
    id "io.freefair.lombok" version "9.5.0"
}

group 'tech.aomi.common'
version '1.0.2-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(26)
    }
}

repositories {
    mavenCentral()
    maven {
        url "https://nexus.stelarx.tech/repository/maven-snapshots/"
    }
}

dependencies {
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
            versionMapping {
                allVariants {
                    fromResolutionResult()
                }
            }
        }
    }
    repositories {
        maven {
            url = project.version.endsWith('-SNAPSHOT')
                    ? 'https://nexus.stelarx.tech/repository/maven-snapshots/'
                    : 'https://nexus.stelarx.tech/repository/maven-releases/'
            credentials {
                username System.getenv('REPO_USERNAME')
                password System.getenv('REPO_PASSWORD')
            }
        }
    }
}
